apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:kFs9JYSLxf6DI8WlA3lnxdOscNX5XV42+3AddH/PK/60Ww9zhj2svocYJy0IH1eXrs+6tTSgsO284jfRyq7g/QxpnvWsOdJCSQHFtniAsfSsJ0K162H001/QAGxe0+2Q7NgRo5XAJAKt6HcNTKXtutTB6yWXPXqzmhi92a6J28767A3/GzcP3iphsaydiz2CYrbPdebGwgn9anBSitwJP9CIcG1L9U+BrCXMVylub0u4aD2oMnJLpWMealD8T206PN+TgFrfUsDjZur0kbdcqKsHKmRZ2DpKd51gR5zNfO179G5uYIeB4z0SGGw=,iv:ZHXdIVEDZUKtU2KOeu+CIeLgBm3iXPUEf7tITGGRta0=,tag:XQsMKqVpU8tIPLWpU2ONhg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1a0xr84tcmzhnm6qsv3ar3pc80pnf84p9gaqv329kmkxktynkna0sh50rp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTkh1WXdzWlFZdVkvYzBZ
            WFVVWnI3TFlSV093cEJ6ZlRkUENKQlRpTW53CmdNK3QwTXNJK1hzZG5iZXNSUm5I
            N2hZME91VjlxM2xncmMrc0ZMcFFpRWsKLS0tIGZoWG1UNmxDSGUwVHcwZmNTWnQw
            VmtXRHNsRDIxb3NoZXRrN2hhZjRWdWcKXC5oAQy0cAf2yVF5lNe0hwwqNK5Jp4J4
            YkGvDdyE3MHcgraij1aHEosWxNjIv6jYd7VGaWvXGILDSwfGjC2zow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T09:07:47Z"
    mac: ENC[AES256_GCM,data:Wwgyfzq8ib9tc69eKIIQ+LKOrlI6O069VWPidDllTKxCtUiFuN7yfcS5KruvZ5jMRXDoIZ6YqKV8P2bGAjM+xWFhJq+XfUZZXf4rJ/xydxAliIsCi1FXIzE0vXzuHI8DmIpaGXml6RSrr+KRMulGoJcgUwsiw775q9nTYkkiHr8=,iv:dlv7JnO1averLmf4rNBBHeRypLTlOOp1yyhv0E3j608=,tag:kKWPA0mYJlGEmWhH4zk0fQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
