apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:7LeijYiyXT4iG8Lpbg0mn3/GMESFI9b4Q5lHt6hi7vpcLQXBJgpwor6CI0rH1YVasw3ATKIE48c9X+QKmb0a2b/c1up+3FZyDJ+q4u3ovggAwaTSAq4uwHLDUxGhG2Lh5hyhtMerb2F+tzuso7Cem2RTpqzD4px8sHA5ytGMSnbw6CYGAq9KoS0DljZlrV1lkrGuCuLBf9LuDionxxR/GHJ8fP5WmHHQBwHb1EvhBpNu6CRbM0syG/EmBExowflxvgkLVicOwBUpptnnZ2s/ihKSrNwtr5Kpeewh93ve70r4sFqA4Ru0usloTxw=,iv:Y8IbRSUHglCWtdJgJdxUMBckrnsjAyYEsKNsqJQ4OFY=,tag:UwkziEvjbwFSx/sIDoZ2hg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age18ht6qad4x8vvpmlt9vstpn6s3s2d5wxyypw0lzh9kuzc0hzmwgjsvksz9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeHp2ckx4QkNlSXEybm9s
            ZVRORi9HWWJVa2tKY0E4aDgxVm9LN3pVd0RJCnZKSmVDQ29jdXZoWm9FNEU4SjE1
            UEpGa0w4R1pxeFQ2ZW5TdkUxUkZqSTAKLS0tIGpoSEVjMVNJSFMyMHZOakFsSGtr
            THJTYXoyZ093aHR3eTM3UzJ0RmVyd1UKPP2j7+Xt3wQ4pcq6B9yWZlr3DJ4EbGkl
            4UjODb5duBpfFakBZeYa3vEb5jfoVrzwjsQgZ4uwWaaUvCa4IyOidA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-24T15:14:26Z"
    mac: ENC[AES256_GCM,data:/STGJDuThEs2LZsbPK3l62vchnRzP2/PPJuO4mcRXuWIejouQ99iFb4CT3yTFztQs6KvJam7PN/ZrXgjfw4u6vZfv60KnQssXIZkXrEfXGmlUVQw+rM7wQWErErbSMY8veOkQIS0DAa/tEXmm0mBxRx/0UZS3coKK3kA5UPMOBs=,iv:9PyhTapvCqO1SCViSFu1R75n8t7LmevZir3dfnBtHac=,tag:q/UlQ5z1BmER0fPV6Y2Kbw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
