apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secrets
    namespace: nextcloud
type: Opaque
stringData:
    nextcloud-username: ENC[AES256_GCM,data:OUDsiQCU,iv:LWS1JEmLPxEis9Odsfou3QkzmwIXnM8mPwg4fz7gVq8=,tag:EFk4QxvqfNfiCo0X2hZW2g==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:Aoap725gSV3d+wv/jNtwUO6UzfteTV8RwA==,iv:j0k9uNJMmNpePlsu6StH6leVRUtSj/UWNBhpLalF+DY=,tag:MzKdbqzCrBZO93+a4StQvA==,type:str]
    postgresql-password: ENC[AES256_GCM,data:q2zgih4k2qaB1SyImClyLDVFPwgwcfHrKA==,iv:OwZP0EWcs5SpLbLDDAegIFmZlnHZUnB+m/088PJGvDQ=,tag:ivMOoaHpQMb9X1JqJYn6Eg==,type:str]
sops:
    age:
        - recipient: age1a0xr84tcmzhnm6qsv3ar3pc80pnf84p9gaqv329kmkxktynkna0sh50rp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcXdteVZ4MEdxcElZY0VO
            SVo4U0poSjBDbzI5dm5PWE1BSmJzM0ZUOERFCjhVNmRRR0p5QnI1TXBzMUlyY0tQ
            azJCOTB4T2lxU042eHJ6em1sQjBpalkKLS0tIFRRRDhueUZ4OHFRRTA0SGh6aS9O
            ek9EenVJWXZwL2FSb0loMTgzMnFqbzQKiwdy+IQKgEubgxS4CUnUogpdGAX8EYeU
            +QFk/dmAazy2OjdHpR+rmPyxI5jEI/O/f8YKshONOAVfo8Stc8yaGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T17:39:04Z"
    mac: ENC[AES256_GCM,data:o2gew49W4tWhXen2lKEBZUf9ol2Psb7MBedc5QcV2BXsVLbGyExN4nvIJFz1wcun3C55RiWyFle/+9RCvPTv0M49+/txuNticUxwtSXUmIGbUFtvx6vwmdKCND9MT6/CtUjE5zG/26JPPub4tsuauFQCOCtHGip4DA8SxnbkUS4=,iv:XAiDVHENt+UqMLYUA1JtgPXv+q9gq0kLj4Pkkl+VLOA=,tag:R5VFe7ilYWRfWFBelWjI1w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
