apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:aEe9z2HSdQ043uWdHQ1kAtfOAxR9KTU951155UBDQAYCX8+V6sPq7adlJg3yAw3xrmAlWdNzsZLUAIniHA9xM9XgCVhchaZTrbH8j0CmqMF2STFlp+V4UnB0GsUf3MxzfOF2zg/HXJpU1zLlqwg0kEWeFkeLt/7at2AH0CA9fOPhQTaidDg7XcgQNf4sFYEmGrtFfWHg0JfHwPuvB99UutHpZ8Ls9q6ziNslmihJ0LuEq8jFxmWAuRljt3sQk0gT08BDdroti/fuf0LGUGo4aJ0f/FVeoDtsnsYNv7O/URZlU/S+yY1mt3jdOr4=,iv:AHd6U6KB3SVssjkhc5sReK06h5IY1qKFGrxKUONSvC4=,tag:8y9D5HEJrDUV4nIcfba4NA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1a0xr84tcmzhnm6qsv3ar3pc80pnf84p9gaqv329kmkxktynkna0sh50rp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQWtveGpZNlFESExXVHFZ
            SHgzZXJnU05EWjgwR2Z1SFVncmt5dEdtbFVjCmcwM2U1bWxTSUc5ZXIzYXdqSUJj
            ZFR1bXRtOFNGL1FscXRrV0dZbHY4SHMKLS0tIHBwNnhWYTF6Q3RKM3hEUkxOdmFk
            LzUvSExTcEFjdFU4WER1Zkp2OUwzZEEK/IDcxjOys1iQOpA5Pu5zNvha1cvZzFyN
            hU2q0BuDclXdemsv3swxfEth2ji8eCw2m57aKowyrApXDT4NSOAfAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T18:35:49Z"
    mac: ENC[AES256_GCM,data:1/LdWA4zGTcsv9RkAKN0Sde0pc9U5PbLd2j3TOniBy5XqYbulX/BvHSpQWkcopzT+dDqzSbv1cLj1OE5EJ1vsYEuNhsW/hPKe8uLxJjDkuFQfZUpyybAqI9pMTicoNuItPEauL1zEd809W1HxxOq+T9HX2LVbneF/LsQAH30JaM=,iv:LtYpYAbCNfsPbjukjgSQuASZ+nO34gTJ4AupQ/TIA/g=,tag:NrNsgK3KJxszj/MGrohJyA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
