apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:QPdxIO11DijQmfwEtja8/o1wsb1ItFFNqyNAlTbZjcP08NoyVMmNvowHcSUjAD9jIkSp6jqomkBxZ0Jnzwrm72lAY9CxSdx9yU9NKHQjH/Ulg878g4pws3TqSWHV4a/r3HCq1EMR0qmDlg8Rjny6dNPb99H4rvTNwgFUbJHyzr2WPo0VwcsJGSoXfOCNeU/px+3WU7xyj8QRXhhmguex3aVozIuMe2l8xEI8/FEyiTJM3gjF1QJIwjd/ugkqSl0dcrvoOgC4IUDLCd1EnLbU5Eworfj1UgtW/gKaQePU4zpsJFk2gSoIjDcNBiA=,iv:HUNKGgXp0HAZTuousG6+/0l8rdB2t3XU3SSkmXdoGK4=,tag:8kD29YxSJh0ZdokzcxMQKg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age18ht6qad4x8vvpmlt9vstpn6s3s2d5wxyypw0lzh9kuzc0hzmwgjsvksz9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByR003d2QvcjRzRWJ6NDU4
            WnkxUDZTcFpReXFmbyszQm1kMFA4VGR1eFhBCmRYYXNpeDIzSWMwbGRTVDdUc2xX
            emZUVG13dmJyMTluWEYrc0RXRHdQVjQKLS0tIE5kc3dRemVySDhtWVl4Y0hLUjdJ
            eVhabEpRTG9FdmNDUng0Wmthcmp1cTAKkWUE7n77iVnaLx6de4VeyQUdKRqMkoqh
            QbPJDAEPeT863NaMQZCUZwx0R6Dc6aHNqUg713NQxt+zVc1DMTxEEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-13T12:20:09Z"
    mac: ENC[AES256_GCM,data:PeJCfoYxAMcCXQrT4zwMDtTsS4H1Up5YnMI3ZPfpKDtT/PLAIAgI9TY+yM7WQmrf7v94yLVD+R1dwaTsf5kK7YkkMviC0HN6m+rDae7E7G1kpHBB0bVsT5e3B1uSBZ85udW2/1TRzr1GcLaPoJYI2Aic1XkW5RWxOsih/N6aKkY=,iv:SQmLRWEnEFlQvLGkXP+vyN+CB7Ye1B3STr+e8DI9Hic=,tag:wAdR1yu72w3E54EN0uQn6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
