apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:Q9GW0aUbOKWsl714,iv:9h7WtYeycmGkti8niP/cMpQ697Oqynfg3n/4frmwLIY=,tag:z/R8XJ/OAG5JFn3N7stDqg==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:vfLPvdiICikAeguBn4PBcHKIrecZtw90bOSgVA==,iv:bKv2QUYq3mzPnOCEihDMCA7CCbpbur293TLB6ZQ1tt4=,tag:jQ/ZsBlLRp1XsCgifKnsRw==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - recipient: age1a0xr84tcmzhnm6qsv3ar3pc80pnf84p9gaqv329kmkxktynkna0sh50rp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaVRiUTVFbzVpWndnSW96
            RWNFNWFHb0Vodjl5Qm55UGh6aFRlY00rSmdZCldaSUZPeXVPVTZMQXlERlB1eXAz
            YVYwd2x3bHRXR09RaG1IdEtDTFp1bW8KLS0tIG1ob054T1JQRmhXQmtyMzdKU2h4
            S3hUZG5pQ3NGdmFZQzlHUnZxMWF0eG8KoQEtVfMvgUQBjfGMQbGxLnFwVx4vrlgt
            gujaBzAzn22AQrFtdWOR3T3+c7qAt3q8KFTfXVKG9MX5BnuZWbe0sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T14:45:11Z"
    mac: ENC[AES256_GCM,data:STjz6+WAA2zlx2ARPs6guRcYAK4Apwp2iIj1CprcVyzKHL0CSCA/FK9A2Q96UQG3gT+KMbS3fz96dy4AsjJOQeDjn2QB9uJbnedhZUsjFcHKZT4hER9Bz38XQrMjIkRdGpQhXFkg1UuBAFAI+kAPDIvP2cNc/JdAocXiMX80dxs=,iv:qRiYCwd0QgeK8dM6wx53n9tTnCDGAsHCXDQbjwzJ7Dk=,tag:mNfCMNWisl0tNPZuxadq2Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
