apiVersion: v1
data:
    password: ENC[AES256_GCM,data:P7QHo0271Qw=,iv:KOH5p+xsStrS8m/dqrm84ilP+aCxcQ2YU3RrVC5BIQo=,tag:lN/SWwIqSO2PV6diy9UTMQ==,type:str]
    user: ENC[AES256_GCM,data:FIcTt8nfgYo=,iv:6rv0M5l5PECfkP+v0ZRsI0QLceDOKyAMKo+FitSM4ek=,tag:cvZkeap/w0zYkg4yiQPHfg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: test-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18ht6qad4x8vvpmlt9vstpn6s3s2d5wxyypw0lzh9kuzc0hzmwgjsvksz9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMOFpZUWx6NHNYeW40RXNY
            dVdxakFLTDRSWlg3dW1LQ29SUmNDeXVwbXpJClRJWWxET1dtUWp1V2o4MkJtWTJu
            QXBWRXFQbGhnSk1VemJkMFBBamtqaU0KLS0tIEhhY0FtNEFCTEpYMVNxQTZLVWk5
            eVhEUmxlUUxScFFKN2ZwL2llcFozM00KH6PEMSdBmrAgVHVFuUVe2y7P07lp2PMx
            kmn2DqHMemjpuUQ0B3fVTy5d7G6anlQXAG511+yo0Ev8mJC9OfgMlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-21T05:55:41Z"
    mac: ENC[AES256_GCM,data:zofQU/cgIY0La39B5Ao/opOsR6CmITOnYQzd2ef/YPEow799bZG3HPpKJsK63PRohReZgfLO0g7lfXrumKQ2VgU8crTtCiU9KGFWQEA+t0Bd5S8hIzyRqGO+h3P0KKQx1nZEk55thsjxzjlUjL5F9ZOhqb5ZIqRYNwg+FK3xUdI=,iv:ROgHIPUiSjkdR5cAaPc1UwaBOzTHyib+quC2Gcimdf0=,tag:eGWmBOqXJQOsZOymAGUoTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
