apiVersion: v1
data:
    cloudflare.json: ENC[AES256_GCM,data:/FTI5I87uJHKRKmQbtEdTMuQo06bbPqpmSzvlgyjdl2R7ioOvFxyAqZQPDlFVOTWJ+HTamtnzcf6CzpqGS2ZaOr0PwpdK9A4aQlwF/LyP3IW8w/6mwSpR2QbChJa0ZWCJUyZLYJqqcfZE+Tr1OtQYKM6dEkvvuNYFnl5SBAfkxAh91RMYkktfmdP7k+XbnlTiCI05vaunBqJOz6ZDzoVctyfl7q8VGIKNbRJ1FVehNiePURXlLIC4hjLFjuWXQSVExRnDZXsYrvKwFQDR+QsKmej6WBatFev,iv:CjZ0boHwtUIx6NCSwIZuxGkwVVMw1hvw07WN0tfIrXc=,tag:pYneapKzL7LpUpMMFlXzSw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age18ht6qad4x8vvpmlt9vstpn6s3s2d5wxyypw0lzh9kuzc0hzmwgjsvksz9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSE1hNk13V3VQUDNMZVhQ
            VGhPS1NWRTZtTmc1azloaUpya24rQkJlcDFRCm9XYXlkbDdrdmU3aFdLbGY1VFFS
            UWlSdm1BbGM3NVdkaWNxa1c4TnlJVkUKLS0tIDZiazVER2EyUm1PN3hrekNvLzdH
            OC83UWRyQXMxcDZOc0ovTndvRFY5QkEKRvsmrwGFhmqGmQwqZif2w0sV+ZlugDmc
            VId5iAD+lGslnvK5qBmLUZ4Y8KVOjFHs3aGGF674s1bZJNLd5ZQt8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-07T16:19:58Z"
    mac: ENC[AES256_GCM,data:9EMECDNyfzh1l/+0wu7reCy/Q1bx6zoqN55CGYUnTzbxJQvf3x2KolcffZF0SljnizurEFIglSB+Zk7ruLS8HljYdTpBJ6uSGZWyBVNBRky3QJmmfhgG+OwxninpC7CwVSZhWaEcMAEQz/5oV+/yrSJHpNPkTkq+Z19b8OxmzNc=,iv:CXTDKirLRinzwLbkUjStlra3vFe6O1xWZiDVapFU0HM=,tag:r1PJUkyahXtmkxifJWL/JA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
