apiVersion: v1
kind: Namespace
metadata:
  name: democratic-csi
  labels:
    # talos doesn't allowe privileged as default, it stops the ds from starting
    pod-security.kubernetes.io/enforce: privileged 
