apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs
  namespace: democratic-csi
spec:
  interval: 5m
  timeout: 15m
  chart:
    spec:
      chart: democratic-csi
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: democratic-csi
  valuesFrom:
  - kind: Secret
    name: truenas-api-key
    valuesKey: apiKey
    targetPath: driver.config.httpConnection.apiKey
  values:
    controller:
      externalAttacher:
        resources:
          requests:
            cpu: 10m
            memory: 50M
            ephemeral-storage: 100Mi
          limits:
            memory: 100Mi
            ephemeral-storage: 200Mi
      externalProvisioner:
        resources:
          requests:
            cpu: 10m
            memory: 50M
            ephemeral-storage: 100Mi
          limits:
            memory: 100M
            ephemeral-storage: 200Mi
      externalResizer:
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 100Mi
            ephemeral-storage: 200Mi
      externalSnapshotter:
        resources:
          requests:
            cpu: 10m
            memory: 30Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 100Mi
            ephemeral-storage: 200Mi
      driver:
        image:
          registry: docker.io/democraticcsi/democratic-csi
          tag: next
          pullPolicy: Always
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 100Mi
            ephemeral-storage: 200Mi
    csiProxy:
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
          ephemeral-storage: 100Mi
        limits:
          memory: 100Mi
          ephemeral-storage: 200Mi
    csiDriver:
      name: "nfs"
    storageClasses:
      - name: nfs
        defaultClass: true
        reclaimPolicy: Retain
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: nfs
          detachedVolumesFromSnapshots: "false"
        mountOptions:
          ["nfsvers=4.2", "nconnect=8", "hard", "noatime", "nodiratime"]
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:
    driver:
      config:
        driver: freenas-api-nfs
        instance_id:
        httpConnection:
          protocol: http
          host: 192.168.178.59
          port: 80
          allowInsecure: true
          apiVersion: 2
        zfs:
          datasetParentName: treasure-chest/k8s/nfs/v
          detachedSnapshotsDatasetParentName: treasure-chest/k8s/nfs/s
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: 0
          datasetPermissionsGroup: 0
        nfs:
          shareHost: 192.168.178.59
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: []
          shareMaprootUser: root
          shareMaprootGroup: root
          shareMapallUser: ""
          shareMapallGroup: ""
    node:
      driver:
        image:
          registry: docker.io/democraticcsi/democratic-csi
          tag: next
          pullPolicy: Always
        resources:
          requests:
            cpu: 30m
            memory: 100Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 200Mi
            ephemeral-storage: 200Mi
      driverRegistrar:
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 200Mi
            ephemeral-storage: 200Mi
      cleanup:
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 200Mi
            ephemeral-storage: 200Mi
