apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: truenas-nfs
  namespace: democratic-csi
spec:
  interval: 30m
  chart:
    spec:
      chart: democratic-csi
      version: '>=0.14.0'
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: democratic-csi
      interval: 12h
  values:
    csiDriver:
      name: "org.democratic-csi.nfs"

    storageClasses:
    - name: truenas-nfs
      defaultClass: true
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: nfs
      mountOptions:
      - nfsvers=4
      - nconnect=8
      - hard
      - noatime
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:

    - name: truenas-nfs-media
      defaultClass: false
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: nfs
      mountOptions:
      - nfsvers=4
      - nconnect=8
      - hard
      - noatime
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:

    volumeSnapshotClasses: []

    driver:
      config:
        driver: freenas-nfs
        instance_id:
        httpConnection:
          protocol: http  # Change to https if SSL configured
          host: 192.168.178.59  # YOUR TRUENAS IP
          port: 80  # Change to 443 for https
          apiKey: truenas-api-key
          allowInsecure: true
        zfs:
          datasetParentName: treasure-chest/k8s  # CHANGE THIS
          detachedSnapshotsDatasetParentName: "{datasetParentName}/snapshots"
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetPermissionsMode: "0770"
          datasetPermissionsUser: 0
          datasetPermissionsGroup: 0
        nfs:
          shareHost: 192.168.178.59  # YOUR TRUENAS IP
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: []
          shareMaprootUser: root
          shareMaprootGroup: root
          shareMapallUser: ""
          shareMapallGroup: ""

    controller:
      driver:
        image: docker.io/democraticcsi/democratic-csi:latest
      externalProvisioner:
        image: registry.k8s.io/sig-storage/csi-provisioner:v5.1.0
      externalResizer:
        image: registry.k8s.io/sig-storage/csi-resizer:v1.12.0
      externalSnapshotter:
        enabled: false

    node:
      driver:
        image:
          registry: docker.io
          repository: democraticcsi/democratic-csi
          tag: latest
      driverRegistrar:
        image:
          registry: registry.k8s.io
          repository: sig-storage/csi-node-driver-registrar
          tag: v2.12.0
      hostPID: true
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
