apiVersion: v1
kind: Secret
metadata:
    name: truenas-api-key
    namespace: democratic-csi
type: Opaque
stringData:
    apiKey: ENC[AES256_GCM,data:hYbOjBCmDN/HizJgJK3Xn6/ey7XzBqtJUzfxS4lYrYYGuXOwechs8BI+GghdlUkPPCBwgcKhxp7giqMZtymLD/80,iv:uwOjzXCq4aLagrcHoXOFhXnjp8AascQfnwcXygPCPJY=,tag:S4eGbOWF5WFy3r7T6wAbPw==,type:str]
sops:
    age:
        - recipient: age1a0xr84tcmzhnm6qsv3ar3pc80pnf84p9gaqv329kmkxktynkna0sh50rp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdUM4Y3FiQXZ4YzVXSW83
            QTJMUWRVcFNpdDVXRldoZWpqS203MTE0M0RRCmgwWi9KNkpDVEVGSC9YMEUyeGtT
            VGFWWVlqNHNIVG5FV1djeUtWOTBIbEkKLS0tIDJMMm5EejFJNW5UR3VFNjJQWmNP
            dER3U2NIQy82WlU5aC9uMGlkaHNYbU0KeTIbx6nDe/GJIhOAjQ7zJIoTTNLubl0o
            zGHt8YnTT9CJrTI8SGNecD696c7LA+rcqMqefkubu0kJb1YTsRU1VA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T07:18:52Z"
    mac: ENC[AES256_GCM,data:MnH770UVNteEnisIRPl9CyLDgvPgGoa4+ypJhTqDoq/6vDL54BKZqW3PGAMKeGW0g/ZpJTbsLtUaT+iCgZMBUkmPM7jssodSwT7FUPTei0I9ZjxdeoOTGAWlkl8U/k4D2G5xEzebutFbpwi6JbRWWCMlv2kAVNRYO0B+D9Amjpo=,iv:1hi7Jihn3WRebF3X/oIcQQnsCnrZ70qaWp3M5ri73l4=,tag:bVuBkv38piLdRd1EzkSH+g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
