apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    oauth.yaml: ENC[AES256_GCM,data:jYs9TcrGMQuzMu0f1vhVfxDnt2L++p3ZKJZ3RIOzqMxNecUEY4p8qKuYdrRMhGdptPswZ9C4DvHZjVPQFRSwC/5y9idLE0ZQSkgAy/7HgBKkknsTOsWXbluZl+LzqGWdHGHTZRyXylCQ6FcSKYDf6Dnp2UxsPfE=,iv:/7NooyDSRW1O1hswFsV+3OaUHBTNaG7rd19Ch+A/+GI=,tag:0IrioEI9z0YtjwJPQ7yOhg==,type:str]
sops:
    age:
        - recipient: age1a0xr84tcmzhnm6qsv3ar3pc80pnf84p9gaqv329kmkxktynkna0sh50rp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYk1iRitnbVJ6Tnd2bkw1
            MG1zRmQ3RDlFbWVQNTg4ejJveFhGOXNhQ3ljCnZlUjNnTjRFdTFxUndydnpTY2p6
            L2VKSnJncGc5bTNVT1U5Y0RUaWN3c1EKLS0tIFJkU01CVTdHSjVTQ2cyVTcxekdr
            S2E4V3Z6ZUpoRGd1b3RqbjYrRDV2YkEKQu9hH3Q/no7HsycMBzArVFEylHi6ls/Q
            579Jec52VcXzIDPi/Xfy0MEwRdsxg/tyM9Q8yDw0MeRjhSDhCq3hDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T14:59:05Z"
    mac: ENC[AES256_GCM,data:8bZu1kq0J5GcKDEjvEqYZ+MHfsODVKwVgyCkWiPJCCJuW2KfEevvjhnT2p46iVT5LTkRZV8Kr5eainMXNK6FynfhG9vGso2/TIIXMkMN+KinKBg3kfyayIk7OaZeKq9OqxYZdpUscvEl8FUuhCjBSdSI7SBdj8Us8cv+hyPRW7Q=,iv:ptfcngFtLU9eh06yHepzw6ejCiBRgTv5Hmh4/34TH58=,tag:VDrgYBvlU2ovNtZCaTEiCg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
