apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:SigxxlD/05uiEs5SNRxm5DIWEjSK3QeteT48Y52JfPl7GXyBHVB/UGgniLxrNDpWlU5JLelcE7Dfczd2a5+W0+mxDVquvx7K0B+CXoEC6d9r3krLywtqjVA3eX04BdmRGES3rN+IsOQSRm4CLphqtZ/NJnKVrM6Ibh2ZhRC3jQhadCb269UPrhamoIcmN+wxqNMf2vgIDcM+taKnzQwd2eLpNRttkNGdh5ewWf8u3sDS7NA4CLjROoZRZ2LTs7H76oGTOhqTs0brSOxrmJ/K9fJg5vVAMUW50MfiNmWMMUoVl22L2cojYA8IDgY=,iv:67TcuA0VN1z3q+6g8LtVZKqeAIdRKE4U5mGXbxo/9qw=,tag:cXsM1hVUAv1k3pUKMX+rXA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1a0xr84tcmzhnm6qsv3ar3pc80pnf84p9gaqv329kmkxktynkna0sh50rp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcUpkNXh0Rk9jdFVpQUJI
            dHRuQldHQmJZZVkxbDNsVlpyUjRKV3RsYWpvCkk3UjBNbnZjRWJRWjVURzlBczdM
            N3EvUnBmelRRSnFDSWJMazl3R2JCMHMKLS0tIHp0dklOaGJvWi8zUmVqUlBCcmFa
            MVJpTXRDdFNOTjBhU1J6QlExQi9xSHcKlMowie+NRM3wUwNXI3Q+2ct0fnYLAYBz
            JcXuEXXkTICyBRVYoUeQe2diGx88l1V/KPVKnklPex/POIu99mDWFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T11:43:26Z"
    mac: ENC[AES256_GCM,data:1k38AAHqc7ZSnTe0vpcjuAuk8KQYXD29gjcGjq2e6BLZjU4eBOW6ly7V3wS7NssTa6xlSBM2sIJ/p+Fy/EMOsPbzuejv4EA0OpnSV10bZq50I5c3NppdRpW5h+Wvh1SHDWWWIk9cFegHn+kX49KIxTVa4miFA+MifKJf0yIOO5A=,iv:RkzDsKABBcBsNAQjgIaS1JDEU5n8/KL1HmszgHU9+rU=,tag:jl0JvgWDVByRMrwIyVvOVA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
