apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 30m
  chart:
    spec:
      chart: nextcloud
      version: "8.9.1"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: nextcloud
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      flavor: apache
    
    # Nextcloud admin credentials from secret
    nextcloud:
      host: nextcloud
      existingSecret:
        enabled: true
        secretName: nextcloud-secrets
        usernameKey: nextcloud-username
        passwordKey: nextcloud-password
      
      extraEnv:
        - name: OVERWRITEPROTOCOL
          value: "https"
      
      # ADD: Security context for the pod
      podSecurityContext:
        fsGroup: 33  # www-data group
        fsGroupChangePolicy: "OnRootMismatch"
      
      # ADD: Security context for the container
      # securityContext:
      #   runAsUser: 33  # www-data user
      #   runAsGroup: 33
      #   runAsNonRoot: true
    
    # Enable persistence with your PVC
    persistence:
      enabled: true
      existingClaim: nextcloud-data
      accessMode: ReadWriteMany
    
    # DISABLE internal database (SQLite)
    internalDatabase:
      enabled: false
    
    # ENABLE external database (PostgreSQL)
    externalDatabase:
      enabled: true
      type: postgresql
      host: nextcloud-postgresql
      database: nextcloud
      user: nextcloud
      existingSecret:
        enabled: true
        secretName: nextcloud-secrets
        passwordKey: postgresql-password
    
    # PostgreSQL subchart configuration
    postgresql:
      enabled: true
      global:
        postgresql:
          auth:
            username: nextcloud
            database: nextcloud
            existingSecret: nextcloud-secrets
            secretKeys:
              adminPasswordKey: postgresql-postgres-password
              userPasswordKey: postgresql-password
      primary:
        persistence:
          enabled: true
          existingClaim: nextcloud-postgres
    
    # Redis for caching
    redis:
      enabled: true
      auth:
        enabled: true
        existingSecret: nextcloud-secrets
        existingSecretPasswordKey: redis-password
      master:
        persistence:
          enabled: false
    
    # Resources
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 2Gi
    
    # Cronjob
    cronjob:
      enabled: true
      type: sidecar
