apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client  # or whatever your NFS storage class is
  resources:
    requests:
      storage: 100Gi  # Adjust based on your needs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-postgres
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
