apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baikal-data
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # tiny — it's just SQLite + ical files
