apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-config-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
