apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
